# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-06 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts/%Y/%m/%d/', verbose_name='Изображение поста'),
        ),
    ]
