# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-08 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='themes',
            name='image',
            field=models.ImageField(blank=True, upload_to='themes/%Y/%m/%d/', verbose_name='Изображение темы'),
        ),
    ]
