# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-09 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_filt'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='filt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.Filt', verbose_name='Фильтр'),
            preserve_default=False,
        ),
    ]
