# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-09 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_filt'),
    ]

    operations = [
        migrations.AddField(
            model_name='filt',
            name='longname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
