# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-09 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_filt_longname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='filt',
        ),
        migrations.AddField(
            model_name='product',
            name='hit',
            field=models.BooleanField(default=1, verbose_name='Хит продаж'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=1, verbose_name='Новые'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='promo',
            field=models.BooleanField(default=2, verbose_name='Акция'),
            preserve_default=False,
        ),
    ]
