# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-16 07:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20160808_0543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='order',
            name='mobile',
            field=models.CharField(default=datetime.datetime(2019, 4, 16, 7, 3, 34, 194483, tzinfo=utc), max_length=50, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='surname',
            field=models.CharField(default=datetime.datetime(2019, 4, 16, 7, 3, 47, 650452, tzinfo=utc), max_length=50, verbose_name='Отчество'),
            preserve_default=False,
        ),
    ]
